name: Performance Issue
description: Report performance problems like slow loading or high resource usage
title: "[PERFORMANCE] "
labels: ["performance", "bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us keep the BrowsePing website fast and efficient! Please describe the performance issue below.

  - type: textarea
    id: description
    attributes:
      label: Performance Issue Description
      description: Describe the performance problem you're experiencing
      placeholder: What's slow or using too much resources?
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Type of Performance Issue
      description: What kind of performance problem is this?
      options:
        - Slow page loading
        - Slow animations/transitions
        - Layout shift/jank
        - Large bundle size
        - Slow API responses
        - Memory leak
        - High CPU usage
        - Unoptimized images
        - Other
    validations:
      required: true

  - type: dropdown
    id: page-affected
    attributes:
      label: Affected Page/Section
      description: Where are you experiencing this performance issue?
      options:
        - Homepage
        - About Page
        - Leaderboard
        - Contact Page
        - Help/Documentation
        - All Pages
        - Other/Multiple Pages
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: How Often Does This Occur?
      description: How frequently do you experience this issue?
      options:
        - Always/Every time
        - Frequently (more than half the time)
        - Sometimes (occasionally)
        - Rarely
    validations:
      required: true

  - type: textarea
    id: performance-metrics
    attributes:
      label: Performance Metrics
      description: If you have any metrics (Lighthouse scores, load times, etc.), please share them
      placeholder: |
        - Page load time: X seconds
        - Lighthouse Performance score: X/100
        - Time to Interactive: X seconds

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this performance issue?
      placeholder: |
        1. Navigate to ...
        2. Scroll to ...
        3. Notice slow loading...
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Brave
        - Opera
        - Other
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: Device Type
      options:
        - Desktop/Laptop
        - Mobile Phone
        - Tablet
    validations:
      required: true

  - type: dropdown
    id: connection-speed
    attributes:
      label: Internet Connection Speed
      description: What's your approximate internet speed?
      options:
        - Fast (50+ Mbps)
        - Medium (10-50 Mbps)
        - Slow (< 10 Mbps)
        - Unknown
    validations:
      required: true

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix (Optional)
      description: If you have ideas for improving performance, share them here
      placeholder: Potential solutions...

  - type: checkboxes
    id: checklist
    attributes:
      label: Before Submitting
      options:
        - label: I have searched existing issues for similar performance problems
          required: true
        - label: This issue is specifically about performance (not general bugs)
          required: true
        - label: I have tested on a stable internet connection
          required: false
